import { ERROR_NAME } from "../types/error";
import { HTTP_STATUS_CODE } from "../types/http";
import { HTTP_STATUS } from "./HTTP_STATUS";

export const ERROR_STATUS: Record<ERROR_NAME, HTTP_STATUS_CODE> = {
  VALIDATION_ERROR: HTTP_STATUS.VALIDATE,
  AUTH_ERROR: HTTP_STATUS.UNAUTHORIZED,
  PERMISSION_DENIED: HTTP_STATUS.FORBIDDEN,
  NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  CONFLICT: HTTP_STATUS.CONFLICT,
  SERVER_ERROR: HTTP_STATUS.INTERNAL_SERVER,
  BAD_REQUEST: HTTP_STATUS.BAD_REQUEST,
  UNAUTHORIZED: HTTP_STATUS.UNAUTHORIZED,
};
